### ISSUE TITLE
QR codes are not made visible in Firefox

### ISSUE THREAD

**Issue by Nightfirecat** [viljoviitanen/freeotp-export#10]
On [export-xml.html](https://rawgit.com/viljoviitanen/freeotp-export/master/export-xml.html), after selecting a tokens.xml file [such as this example file](https://gist.github.com/Nightfirecat/949b881458c77bc3e2d6500b80116014), only the name of the site/username are made visible, along with a fully-white `<img>`, while the `<canvas>` containing the image data is hidden. Removing the inline CSS hiding the canvas works fine though.

There are only two console lines logged, as follows:

```
Object { algo: "SHA1", counter: 0, digits: 6, issuerExt: "Google", issuerInt: "Google", label: "example@gmail.com", period: 30, secret: (20) […], type: "TOTP" }
export-xml.html:97:5
otpauth://totp/Google%3Aexample%40gmail.com?secret=ZNATJX4LWUXY5P3LOUWHLM74NE236PNT&issuer=Google&algorithm=SHA1&digits=6&period=30 export-xml.html:111:5
```

Additionally, the full source of the page body after processing the example file is as follows:

```
<body><a href="https://github.com/viljoviitanen/freeotp-export">Instructions at GitHub</a>
<br>
FreeOTP XML file: <input id="file" type="file" onchange="onChange(event)"><p></p><div>Google:example@gmail.com</div><div id="0" title="otpauth://totp/Google%3Aexample%40gmail.com?secret=ZNATJX4LWUXY5P3LOUWHLM74NE236PNT&amp;issuer=Google&amp;algorithm=SHA1&amp;digits=6&amp;period=30"><canvas width="256" height="256" style="display: none;"></canvas><img style="display: block;" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAADGUlEQVR4nO3UMQEAAAiAMPuX1hgebAm4mAWy5jsA+GMAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEGYAEHbmUDvFpM58qAAAAABJRU5ErkJggg=="></div>

</body>
```

From this, I would either expect (a) the `<canvas>` with the valid image data is not hidden, and an image tag is not created, or (b) the `<img>` is populated with a valid base-64 png image data corresponding to the QR code shown in the canvas.

P.S. I have adjusted my browser config in some ways that would resist fingerprinting and could be the cause of this. If this issue is not reproduceable in a clean environment, I am happy to investigate these settings further to see if one of them is the cause of this behavior.

**Comment by viljoviitanen** [comment]
Sorry, I've lost interest in this years ago. I'll archive the repository (it can be forked still)
