### ISSUE TITLE
Add image param if exists

### ISSUE THREAD

**Issue by japm48** [viljoviitanen/freeotp-export#6]
FreeOTP supports an image in the QR URL.
See commit freeotp/freeotp-android@e1dbb3c6c3faf112a4bebb75057e0f739c52ac97, in particular [this line](https://github.com/freeotp/freeotp-android/blob/0c6af8d639e6a6bbe259748c639a6b056598034c/app/src/main/java/org/fedorahosted/freeotp/Token.java#L125).

Example of a real XML `string` entry (edited for obvious reasons):
```
<string name="OVH:EDITED-ovh">
{"algo":"SHA1","counter":0,"digits":6,"image":"https://www.ovh.com/images/totp/ovh.png","issuerExt":"OVH","label":"EDITED-ovh","period":30,"secret":[0,0,0,0,0,0,0,0,0,0],"type":"TOTP"}
</string>
```

It would be helpful to be able to backup and restore this (now it reverts to the default image).

I guess it only requires adding an optional field to `params`.

**Comment by viljoviitanen** [comment]
https://github.com/google/google-authenticator/wiki/Key-Uri-Format (which is the only document I know about the qr code format) does not mention an image url can be in the qr code, and I'm not sure if adding nonstandard fields in the qr code url is a good idea, even if freeotp supports it. If someone considers doing this, before sending a pull request to me, be sure to test the resulting qr code and document the results on authenticator apps on different phones, even old ones (at least the ones I've mentioned in the README).

Closing for now.
